# Generated by Django 5.2.7 on 2026-01-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_groupproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalsequence',
            options={'verbose_name_plural': 'Group Projects'},
        ),
        migrations.AddField(
            model_name='approvalsequence',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalsequence',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AddField(
            model_name='approvalsequence',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AddField(
            model_name='group',
            name='academic_year',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.department'),
        ),
        migrations.AlterField(
            model_name='group',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.project'),
        ),
        migrations.AlterField(
            model_name='groupcreationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='approvalsequence',
            unique_together={('group', 'project')},
        ),
        migrations.CreateModel(
            name='ProgressPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colleges', models.ManyToManyField(blank=True, help_text='Colleges using this pattern', related_name='progress_patterns', to='core.college')),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments using this pattern', related_name='progress_patterns', to='core.department')),
            ],
            options={
                'verbose_name_plural': 'Progress Patterns',
            },
        ),
        migrations.CreateModel(
            name='DepartmentProgressPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Marks this pattern as default for the department')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_patterns', to='core.department')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_patterns', to='core.progresspattern')),
            ],
            options={
                'verbose_name_plural': 'Department Progress Patterns',
                'unique_together': {('department', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='CollegeProgressPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Marks this pattern as default for the college')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_patterns', to='core.college')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_patterns', to='core.progresspattern')),
            ],
            options={
                'verbose_name_plural': 'College Progress Patterns',
                'unique_together': {('college', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='ProgressStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('max_mark', models.FloatField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.progresspattern')),
            ],
            options={
                'verbose_name_plural': 'Progress Stages',
                'ordering': ['order'],
                'unique_together': {('pattern', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='GroupProject',
        ),
    ]
