# Generated by Django 5.2.7 on 2026-01-07 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_approvalsequence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresspattern',
            options={},
        ),
        migrations.AlterModelOptions(
            name='progressstage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='progressstage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='progresspattern',
            name='colleges',
        ),
        migrations.RemoveField(
            model_name='progresspattern',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='progresspattern',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='progresspattern',
            name='description',
        ),
        migrations.RemoveField(
            model_name='progresspattern',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='progresspattern',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='progresspattern',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='progressstage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressstage',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PatternStageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('max_mark', models.FloatField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.progresspattern')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.progressstage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('pattern', 'order'), ('pattern', 'stage')},
            },
        ),
        migrations.AddField(
            model_name='progresspattern',
            name='stages',
            field=models.ManyToManyField(related_name='patterns', through='core.PatternStageAssignment', to='core.progressstage'),
        ),
        migrations.RemoveField(
            model_name='progressstage',
            name='max_mark',
        ),
        migrations.RemoveField(
            model_name='progressstage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='progressstage',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='progressstage',
            name='stage_name',
        ),
    ]
