# Generated by Django 5.2.7 on 2026-01-11 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_group_created_at_group_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSubStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('max_mark', models.FloatField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_stages', to='core.progressstage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('stage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PatternSubStageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('max_mark', models.FloatField(blank=True, null=True)),
                ('pattern_stage_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_stage_assignments', to='core.patternstageassignment')),
                ('sub_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.progresssubstage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('pattern_stage_assignment', 'order'), ('pattern_stage_assignment', 'sub_stage')},
            },
        ),
    ]
