# Generated by Django 5.2.7 on 2026-01-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_progresssubstage_patternsubstageassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, help_text='Teacher-assigned score', null=True)),
                ('notes', models.TextField(blank=True, help_text='Teacher or student notes', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.group')),
                ('pattern_stage_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.patternstageassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
                ('sub_stage_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.patternsubstageassignment')),
            ],
            options={
                'verbose_name_plural': 'Student Progress Records',
                'unique_together': {('student', 'group', 'pattern_stage_assignment', 'sub_stage_assignment')},
            },
        ),
    ]
