# Generated by Django 5.2.7 on 2026-01-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studentprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
