# Generated by Django 5.2.7 on 2026-01-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='related_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.approvalrequest'),
        ),
    ]
